// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiddauoobtdljrlamqma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpZGRhdW9vYnRkbGpybGFtcW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDIzNTcsImV4cCI6MjA2MDk3ODM1N30.tIjacLx0ASb01Cs1vDaHONMd8pnVxCqXbdQx5QoWo0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);